<?php
/**
 * Created by PhpStorm.
 * User: misha
 * Date: 20.09.16
 * Time: 23:06
 */

namespace vysochin\yamarket;

/**
 * Class Market
 * @package vysochin\yamarket
 */
  class Market extends \yii\base\Widget
{
    private $config = [];

    public function run()
    {
        var_dump(22);die;
        parent::run(); // TODO: Change the autogenerated stub
    }
}